In [1]:
import pandas as pd
import json
import time
import requests
from googletrans import Translator
import random
translator = Translator(service_urls=['translate.google.com'])

In [6]:
excel_file_path = '../data/raw/color_coding_semantic_segmentation_classes.xlsx'
df = pd.read_excel(excel_file_path)
# Load the JSON file
json_url = "https://huggingface.co/datasets/huggingface/label-files/resolve/main/ade20k-id2label.json"
json_data = requests.get(json_url).json()

In [7]:
df

,Idx,Ratio,Train,Val,Stuff,"Color_Code (R,G,B)",Color_Code(hex),Color,Name
0,1,0.1576,11664,1172,1,"(120, 120, 120)",#787878,NaN,wall
1,2,0.1072,6046,612,1,"(180, 120, 120)",#B47878,NaN,building;edifice
2,3,0.0878,8265,796,1,"(6, 230, 230)",#06E6E6,NaN,sky
3,4,0.0621,9336,917,1,"(80, 50, 50)",#503232,NaN,floor;flooring
4,5,0.0480,6678,641,0,"(4, 200, 3)",#04C803,NaN,tree
...,...,...,...,...,...,...,...,...,...
145,146,0.0003,130,14,0,"(0, 133, 255)",#0085FF,NaN,shower
146,147,0.0003,178,28,0,"(255, 214, 0)",#FFD600,NaN,radiator
147,148,0.0002,504,57,0,"(25, 194, 194)",#19C2C2,NaN,glass;drinking;glass
148,149,0.0002,775,96,0,"(102, 255, 0)",#66FF00,NaN,clock
149,150,0.0002,421,56,0,"(92, 0, 255)",#5C00FF,NaN,flag